<template>
  <div>
    <vb-title
      id="Basic"
      type="title"
    >Basic:</vb-title>
    <vb-box>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="128x128"
      ></vb-image>
    </vb-box>
    <vb-title
      id="Type"
      type="title"
    >Type:</vb-title>
    <vb-box>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="128x128"
        rounded
      ></vb-image>
    </vb-box>
    <vb-title
      id="Size"
      type="title"
    >Size:</vb-title>
    <vb-box>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="16x16"
      ></vb-image>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="24x24"
      ></vb-image>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="32x32"
      ></vb-image>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="48x48"
      ></vb-image>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="64x64"
      ></vb-image>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="96x96"
      ></vb-image>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="128x128"
      ></vb-image>
    </vb-box>
    <vb-title
      id="Ratios"
      type="title"
    >Responsive images with ratios:</vb-title>
    <vb-box>
      <vb-image
        path="https://bulma.io/images/placeholders/480x480.png"
        size="square"
      ></vb-image>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="1by1"
      ></vb-image>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="5by4"
      ></vb-image>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="4by3"
      ></vb-image>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="3by2"
      ></vb-image>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="5by3"
      ></vb-image>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="16by9"
      ></vb-image>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="2by1"
      ></vb-image>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="3by1"
      ></vb-image>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="4by5"
      ></vb-image>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="3by4"
      ></vb-image>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="2by3"
      ></vb-image>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="3by5"
      ></vb-image>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="9by16"
      ></vb-image>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="1by2"
      ></vb-image>
      <vb-image
        path="https://bulma.io/images/placeholders/128x128.png"
        size="1by3"
      ></vb-image>

    </vb-box>
  </div>
</template>

<script>
export default {
  name: 'ImageExamples'
}
</script>
