<template>
  <div class="container">
    <vb-title
      id="Basic"
      type="title"
    >Basic:</vb-title>
    <vb-box>
      <vb-progress></vb-progress>
    </vb-box>
    <vb-title
      id="Colors"
      type="title"
    >Colors and value:</vb-title>
    <vb-box>
      <vb-progress
        color="primary"
        value="10"
        max="100"
      ></vb-progress>
      <vb-progress
        color="info"
        value="20"
        max="100"
      ></vb-progress>
      <vb-progress
        color="success"
        value="30"
        max="100"
      ></vb-progress>
      <vb-progress
        color="warning"
        value="40"
        max="100"
      ></vb-progress>
      <vb-progress
        color="danger"
        value="50"
        max="100"
      ></vb-progress>
      <vb-progress
        color="white"
        value="60"
        max="100"
      ></vb-progress>
      <vb-progress
        color="light"
        value="70"
        max="100"
      ></vb-progress>
      <vb-progress
        color="dark"
        value="80"
        max="100"
      ></vb-progress>
      <vb-progress
        color="black"
        value="90"
        max="100"
      ></vb-progress>
      <vb-progress
        color="link"
        value="100"
        max="100"
      ></vb-progress>
    </vb-box>
    <vb-title
      id="Sizes"
      type="title"
    >Sizes:</vb-title>
    <vb-box>
      <vb-progress
        color="primary"
        size="small"
        value="10"
        max="100"
      ></vb-progress>
      <vb-progress
        color="primary"
        value="20"
        max="100"
      ></vb-progress>
      <vb-progress
        color="primary"
        value="40"
        max="100"
        size="medium"
      ></vb-progress>
      <vb-progress
        color="primary"
        value="80"
        max="100"
        size="large"
      ></vb-progress>
    </vb-box>
  </div>
</template>

<script>
export default {
  name: 'ProgressExamples'
}
</script>
<style>
</style>
